
MODE_DEV = "dev"
MODE_PROD = "prod"
MODE_TEST = "test"

VAULTS_BASE_DIR = "./data"

JWT_ISS = "backend"
JWT_AUD = "client"
JWT_ALGORITHMS = "HS256"
JWT_SECRET = "secret"
JWT_SCOPES = "open"


ACCOUNT_SID = "YOUR_ACCOUNT_SID"
ACCOUNT_TOKEN = "YOUR_ACCOUNT_TOKEN"
APPID = "YOUR_ACCOUNT_TOKEN"
TEMPLAYE_ID = "1"
